# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- v3
- master

variables:
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

pool:
  vmImage: 'windows-2019'
  
steps:
- checkout: self
  submodules: true
- task: UseDotNet@2
  inputs:
    version: '3.1.x'
  
- task: PowerShell@2
  displayName: "Use Java 11 by default"
  inputs:
    targetType: 'inline'
    script: |
      $jdkPath = 'C:\Program Files\Java\zulu-11-azure-jdk_11.33.15-11.0.4-win_x64'
      Write-Host "##vso[task.setvariable variable=JAVA_HOME]$jdkPath"
  
- task: DotNetCoreCLI@2
  displayName: Restore Nuget packages
  inputs:
    command: restore
    projects: '**/VnManager.csproj'
    
- task: Cache@2
  displayName: Cache NuGet packages
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**'
    restoreKeys: |
       nuget | "$(Agent.OS)"
    path: $(NUGET_PACKAGES)  

- task: SonarCloudPrepare@1
  displayName: 'Prepare for SonarCloud Scan'
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'micah686'
    scannerMode: 'MSBuild'
    projectKey: '$(SONAR_CLOUD_KEY)'
    projectName: 'VnManager'

- task: DotNetCoreCLI@2
  displayName: Build and Publish
  inputs:
    command: publish
    projects: '**/*VnManager.csproj'
    publishWebProjects: false
    arguments: '-c Release --output ./$(Build.SourcesDirectory)' # Update this to match your need
    zipAfterPublish: True

- task: CopyFiles@2
  displayName: 'Copy Files to: Staging Directory'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '$(Build.SourcesDirectory)\*.zip'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud analysis'

- task: SonarCloudPublish@1
  displayName: 'Publish results on build summary'
  inputs:
    pollingTimeoutSec: '300'