# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-2019'
  
steps:
- checkout: self
  submodules: true
- task: UseDotNet@2
  inputs:
    version: '3.1.x'
  
- task: PowerShell@2
  displayName: "Use Java 11 by default"
  inputs:
    targetType: 'inline'
    script: |
      $jdkPath = 'C:\Program Files\Java\zulu-11-azure-jdk_11.33.15-11.0.4-win_x64'
      Write-Host "##vso[task.setvariable variable=JAVA_HOME]$jdkPath"
  
- task: DotNetCoreCLI@2
  displayName: Restore Nuget packages
  inputs:
    command: restore
    projects: '**/VnManager.csproj'
    
- task: Cache@2
  displayName: Cache NuGet packages
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**'
    restoreKeys: |
       nuget | "$(Agent.OS)"
    path: $(NUGET_PACKAGES)  

- task: SonarCloudPrepare@1
  displayName: 'Prepare for SonarCloud Scan'
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'micah686'
    scannerMode: 'MSBuild'
    projectKey: '$(SONAR_CLOUD_KEY)'
    projectName: 'VnManager'

- task: DotNetCoreCLI@2
  displayName: Build and Publish
  inputs:
    command: publish
    projects: '**/*VnManager.csproj'
    publishWebProjects: false
    arguments: '-c Release --output ./$(Build.SourcesDirectory)' # Update this to match your need

- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud analysis'

- task: SonarCloudPublish@1
  displayName: 'Publish results on build summary'
  inputs:
    pollingTimeoutSec: '300'